name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Package files
        run: |
          mkdir mosdns-config-${{ steps.get_version.outputs.VERSION }}
          cp -R mosdnsv5/* mosdns-config-${{ steps.get_version.outputs.VERSION }}
          tar -zcvf mosdns-config-${{ steps.get_version.outputs.VERSION }}.tar.gz ./mosdns-config-${{ steps.get_version.outputs.VERSION }}
          zip -r mosdns-config-${{ steps.get_version.outputs.VERSION }}.zip ./mosdns-config-${{ steps.get_version.outputs.VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./mosdns-config-${{ steps.get_version.outputs.VERSION }}.tar.gz
            ./mosdns-config-${{ steps.get_version.outputs.VERSION }}.zip
          draft: false
